FROM httpd:2.4

# Install system dependencies, Ruby, and Passenger
RUN apt-get update && apt-get install -y \
    build-essential \
    zlib1g-dev \
    libssl-dev \
    libyaml-dev \
    libpq-dev \
    curl \
    git \
    gnupg2 \
    libcurl4-openssl-dev \
    libapr1-dev \
    libaprutil1-dev \
    autoconf \
    bzip2 \
    libreadline-dev \
    procps \
    && curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g yarn \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install rbenv and ruby-build
RUN git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv && \
    git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build && \
    chmod -R o+rx /usr/local/rbenv

# Set up rbenv environment
ENV PATH="/usr/local/rbenv/bin:/usr/local/rbenv/shims:$PATH"
RUN echo 'export PATH="/usr/local/rbenv/bin:$PATH"' >> /root/.bashrc && \
    echo 'eval "$(rbenv init -)"' >> /root/.bashrc && \
    . /root/.bashrc && \
    rbenv install 3.3.6 && \
    rbenv global 3.3.6

RUN gem install bundler -v 2.3.26

RUN gem install passenger -v 6.0.27 && \
    passenger-install-apache2-module --auto && \
    passenger-config validate-install --auto && \
    chmod -R o+rx /usr/local/rbenv

# Copy Apache configuration files
COPY conf.d/passenger.conf /usr/local/apache2/conf.d/passenger.conf
COPY conf.d/rails_anki8.conf /usr/local/apache2/conf.d/rails_anki8.conf
COPY httpd.conf /usr/local/apache2/conf/httpd.conf

# Set working directory and copy app
WORKDIR /myapp
COPY . .

# Install app dependencies
RUN bundle install && \
    yarn install

# Precompile assets
ENV RAILS_ENV=production \
    SECRET_KEY_BASE=5db0e2382250d80ae1bc8767501d403ee4ce0ebd7d331d070ddd9306befd71d3ff531b75d04601c5fc2088a557635161133047c6ac23a3146cb898a9f8826e4b
RUN bundle exec rails assets:precompile

# Expose port
EXPOSE 80

# Start Apache
CMD ["httpd-foreground"]
