ServerName localhost

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /app/public

    # Enable Passenger
    PassengerEnabled on
    PassengerAppRoot /app
    PassengerRuby /usr/local/bin/ruby
    PassengerAppEnv production
    PassengerFriendlyErrorPages on

    <Directory /app/public>
        AllowOverride all
        Options -MultiViews
        Require all granted
    </Directory>

    # Enable logging
    ErrorLog /var/log/apache2/rails-app-error.log
    CustomLog /var/log/apache2/rails-app-access.log combined
</VirtualHost>