# /etc/apache2/apache2.conf
ServerRoot /etc/apache2
Listen 80

Include /etc/apache2/mods-enabled/*.load
Include /etc/apache2/mods-enabled/*.conf

Include /etc/apache2/sites-enabled/*.conf

User www-data
Group www-data

DefaultRuntimeDir ${APACHE_RUN_DIR}
PidFile ${APACHE_PID_FILE}

Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

AccessFileName .htaccess
<FilesMatch "^\.htaccess$">
  Require all denied
</FilesMatch>

LogLevel warn
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

<Directory />
  Options FollowSymLinks
  AllowOverride None
  Require all denied
</Directory>

<Directory /myapp/public>
  Options FollowSymLinks
  AllowOverride All
  Require all granted
</Directory>