# /etc/apache2/sites-available/rails_anki8.conf
<VirtualHost *:80>
  ServerName localhost
  DocumentRoot /myapp/public

  <Directory /myapp/public>
    Allow from all
    Options -MultiViews
    Require all granted
  </Directory>

  PassengerAppRoot /myapp
  PassengerAppEnv production
  PassengerBaseURI /

  ErrorLog ${APACHE_LOG_DIR}/rails_anki8_error.log
  CustomLog ${APACHE_LOG_DIR}/rails_anki8_access.log combined
</VirtualHost>